import json
import os
import sys

# --- PATH CONFIGURATION ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(BASE_DIR, '../../config/design_specs.json')
CPP_HEADER_PATH = os.path.join(BASE_DIR, '../cpp/specs.h')

def load_specs():
    if not os.path.exists(CONFIG_PATH):
        print(f"Error: Config not found at {CONFIG_PATH}")
        sys.exit(1)
    with open(CONFIG_PATH, 'r') as f:
        return json.load(f)

def generate_cpp_header(data):
    cpp_content = f"""#ifndef SPECS_H
#define SPECS_H
// Auto-generated by param_manager.py
namespace Specs {{
    const double SIDE_LENGTH = {data['side_length']};
    const double HOLE_DIA = {data['hole_diameter']};
    const double DENSITY = {data['material_density']};
}}
#endif
"""
    os.makedirs(os.path.dirname(CPP_HEADER_PATH), exist_ok=True)
    with open(CPP_HEADER_PATH, 'w') as f:
        f.write(cpp_content)
    print(f"  -> Generated C++ Header: {CPP_HEADER_PATH}")

def update_spec(key, value):
    data = load_specs()
    if key in data:
        try:
            value = float(value)
        except ValueError:
            pass 
        data[key] = value
        with open(CONFIG_PATH, 'w') as f:
            json.dump(data, f, indent=4)
        print(f"  -> Updated JSON: {key} = {value}")
        generate_cpp_header(data)
    else:
        print(f"Error: Key '{key}' not found.")

if __name__ == "__main__":
    if len(sys.argv) > 2:
        update_spec(sys.argv[1], sys.argv[2])
    else:
        print(json.dumps(load_specs(), indent=4))
