#ifndef SPECS_H
#define SPECS_H
// Auto-generated by param_manager.py
namespace Specs {
    const double SIDE_LENGTH = 90.0;
    const double HOLE_DIA = 10.0;
    const double DENSITY = 2.7;
}
#endif
